### PR TITLE
add fetch api based async json parse

### PR DESCRIPTION
**Pull request by nelix**
Follow up from #1 
Not sure if I got the code style right, and I'm also not sure the best way to test this (maybe I should break it into two files?) but here is my first stab at using the request api to process json.

I basically just took what I found here and tried to fit it in nicely: http://azimi.me/2015/07/30/non-blocking-async-json-parse.html

### CODE REVIEW

**Comment by Kikobeats** [comment]
you rocks!

BTW, instead of divide depending if fetch us natively supported in browser, you can use the module [node-fetch](https://github.com/bitinn/node-fetch) as a normal dependency. Later browserify will create the browser version.

**Comment by Kikobeats** [comment]
I was investigating and I'm not sure if this is better than the current code. 

The method in the [node-fetch](https://github.com/bitinn/node-fetch/blob/master/lib/response.js#L42-L48) library is:

``` js
Response.prototype.json = function() {

    return this._decode().then(function(text) {
        return JSON.parse(text);
    });

}
```

and in the in [fetch github library](https://github.com/github/fetch/blob/master/fetch.js#L188-L190):

``` js
    this.json = function() {
      return this.text().then(JSON.parse)
    }
```

In both methods, I think that they are using a sync method inside a async method, simply using a promise interface: you need to wait that the sync method finish to return the promise.

This is similar that the current library code, but from other different point of view: wrap the sync method as async and later use a cb or a promise to return the result.

What do you think?

**Comment by nelix** [comment]
Yeah I figure it's a pretty large dependency, and requires build steps (which I don't mind if there is some gain from it).

But it is your project and I'm happy to change up my PR :)

**Comment by nelix** [comment]
One thing I would like is to test both code paths, but I don't really know how.

**Comment by Kikobeats** [comment]
so finally I prefer don't merge this. The result is the same: not real async method.

**Pull request closed without merging**
